### ISSUE TITLE
Calico 3.19 doesn't properly deallocate assigned IP addresses

### ISSUE THREAD

**Issue by MarioUhrik** [sighupio/fury-kubernetes-networking#27]
In short, please see https://github.com/projectcalico/calico/issues/4861
---

Our setup:
- OCI compute instances with Oracle Linux 7.9
- self-managed K8s cluster, version 1.19, based on `fury-kubernetes-oci`
- latest `fury-kubernetes-networking` and other fury packages
- automation for nightly VM shutdown for cloud cost reduction

After a few weeks of our cluster's existence, Calico runs out of available IPs to assign to new pods.
This situation can be manually repaired with the use of `calicoctl ipam release`.
We've also seen that if we upgrade Calico to 3.20, the problem disappears entirely, and the number of leaked IPs stops growing.
This seems to be related to https://github.com/projectcalico/calico/issues/4861.

In my opinion, the ideal way to resolve this issue would be to upgrade `fury-kubernetes-networking` Calico to 3.20.

Credit and thanks to @elvisprenga and @bernardhalas

**Comment by nandajavarma** [comment]
This issue has been now resolved since `calico` is upgraded to `v3.21.x` in PR #30 . Closing this!
