### ISSUE TITLE
weave-net deprecation

### ISSUE THREAD

**Issue by angelbarrera92** [sighupio/fury-kubernetes-networking#4]
Hi team

As we were having a lot of issues with `weave-net` in some kubernetes cluster, we must consider deprecate it in future module releases. 

Does anyone have a different POV?

**Comment by phisco** [comment]
Totally agree with that. Here a good comparison of the alternatives: https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-updated-april-2019-4a9886efe9c4

**Comment by phisco** [comment]
meanwhile, here a PR to have calico working on AWS https://github.com/sighupio/fury-kubernetes-aws/pull/23 .
