### ISSUE TITLE
Improve Calico monitoring (operated and not operated)

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-kubernetes-networking#48]
For a general improvement on the monitoring side for the fury packages, we need to add alerts and dashboards on Calico, operated and not operated)

**Comment by ralgozino** [comment]
> For a general improvement on the monitoring side for the fury packages, we need to add alerts and dashboards on Calico, operated and not operated)

Metrics and dashboards have been provided for several releases and they were updated and improved in the latest one.

We did not have alerts defined though. I'm Adding alerts in the linked PR.
